repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
      - id: isort
        language_version: python3.9
        args: [--line-length=127]
  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.9
        args: [--line-length=127]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-docstrings,
          flake8-builtins,
          flake8-comprehensions,
          flake8-print,
          flake8-eradicate,
        ]
        language_version: python3.9
        args: [
          --max-line-length=127,
          '--ignore=D100,D101,D102,D103,D104,D105,D106,D107,D200,D210,D401,W503,E203'
        ]
  # See https://stackoverflow.com/questions/61238318/pylint-and-pre-commit-hook-unable-to-import/61238571#61238571
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
          --max-line-length=127,
          --max-args=8,
          --max-statements=64,
          '--disable=too-few-public-methods,logging-fstring-interpolation,too-many-instance-attributes,no-else-return,too-many-locals,no-self-use,duplicate-code,broad-except,unspecified-encoding',
          '--good-names=ts'
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
    -   id: mypy
        verbose: true
        entry: bash -c 'mypy "$@" || true' --
        additional_dependencies: [types-PyYAML, types-requests]
